spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    listener:
      ack-mode: "manual_immediate"
      missing-topics-fatal: false
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: 'com.pachico.arithmetic.domain.Operation'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/liquibase-changelog.yml
    enabled: true

resilience4j.ratelimiter:
  metrics:
    enabled: true
  instances:
    basicExample:
      limit-for-period: 3
      limit-refresh-period: 60s
      timeout-duration: 0s
      allow-health-indicator-to-fail: true
      subscribe-for-events: true
      event-consumer-buffer-size: 50

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

franjagonca:
  openapi:
    local-url: http://localhost:8080
    prod-url: https://localhost:8080
  rest:
    base-url: https://bf2af314-c73f-416a-8e93-26c479a00ecc.mock.pstmn.io

event:
  topic:
    operation:
      created: created.operation
  group:
    persist:
      operation: persist.operation