version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: franjagonca
      POSTGRES_PASSWORD: franjagonca
      POSTGRES_DB: arithmetic
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Kafka service
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: my_kafka_broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka_data:/var/lib/kafka/data

  # ZooKeeper service (required for Kafka)
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: my_zookeeper
    ports:
      - "2181:2181"
