version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: franjagonca
      POSTGRES_PASSWORD: franjagonca
      POSTGRES_DB: arithmetic
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # ZooKeeper service (required for Kafka)
  zookeeper:
    container_name: zookeeper_test
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_merge_net

  # Kafka service
  kafka:
    container_name: kafka_test
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZK_SERVER: zookeeper:2181
      ADVERTISED_HOST: localhost
      CONSUMER_THREADS: 5
      BROKER_ID: 1
      ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka_merge_net

networks:
  kafka_merge_net:
    driver: bridge
